name: App

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish:
    name: Publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: Install workload
        run: dotnet workload install maui-android
      - name: Setup Java SDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
      - name: publish Maui
        run: |
          cd MauiRuntime
          dotnet publish -f:net6.0-android -c:Release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Android App
          path: MauiRuntime/bin/Release/net6.0-android/publish
  sendtotelegram:
    name: Send to Telegram
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Android App
      - name: Send .apk
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: ${{ github.workspace }}/com.companyname.mauiruntime-Signed.apk
