name: end to end tests

on:
  pull_request:
    branches:
      - "**"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install workload
        run: dotnet workload install wasm-tools          
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Publish Blazor webassembly using dotnet
        run: dotnet publish -c Release --no-build 
      - name: Publish generated Blazor webassembly to Netlify
        uses: netlify/actions/cli@master 
        env: 
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=/Webassembly/release/wwwroot 
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
      - name: Run a one-line script
        run: echo The site is deployed to ${{ steps.deployPreview.outputs.NETLIFY_PREVIEW_URL }}
      