name: end to end tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - "**"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1.3
        id: netlifyDeploy
        with:
          site_name: "siteswaps"
          max_timeout: 500          
      - name: Run a one-line script
        run: echo The site is deployed to ${{ steps.waitForNetlify.outputs.url }}
