name: end to end tests

on:
  pull_request:
    branches:
      - "**"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jsmrcaga/action-netlify-deploy@master
        id: deployPreview
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_command: dotnet workload install wasm-tools && dotnet publish -o release -c Release
          
      - name: Run a one-line script
        run: echo The site is deployed to ${{ steps.deployPreview.outputs.NETLIFY_PREVIEW_URL }}
        
      - name: Archive production logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: logs
          retention-days: 1
          path: |
            /home/runner/.npm/_logs/*
            /github/home/runner/.npm/_logs/*
            /github/home/.npm/_logs/*        
