name: build and publish

on:
  pull_request:
    branches:
      - "**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Install workload
        run: dotnet workload install wasm-tools
      - name: Build Solution
        run: dotnet build -c release        
     
      - name: Test
        run: dotnet test -c Release --filter TestCategory!=E2E --no-build
