name: build-and-push

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "juggling"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install workload
        run: dotnet workload install wasm-tools
      - name: run minver
        id: version
        uses: thefringeninja/action-minver@2.0.0-preview1
      - name: New Version
        run: |
          echo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
      - name: Publish
        run: dotnet publish        
      - name: Test
        run: dotnet test --no-build --no-restore
      - name: Login to GithubRegistry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: WebApplication/Dockerfile
          push: true
          tags: "${{ env.REGISTRY }}/sopor10/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}"