name: build-and-push

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "juggling"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install workload
        run: dotnet workload install wasm-tools
      - name: Build Solution
        run: dotnet build -c release  

      - name: Test
        run: dotnet test -c Release --filter TestCategory!=E2E

      - name: install playwright
        run: |
          npm install @playwright/test                                              ║
          npx playwright install
          npx playwright install-deps
          npx playwright install-deps chromium 
      - name: Wait for Netlify Deploy
        uses: probablyup/wait-for-netlify-action@3.2.0
        id: waitForDeployment
        with:
          site_id: ${{ secrets.NETLIFY_SITE_ID }}
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Test
        run: dotnet test -c Release --no-build --filter TestCategory=E2E
        env:
          E2E_TEST_BASEURL: ${{ steps.waitForDeployment.outputs.url }}
          
  publish-docker-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to GithubRegistry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      - name: run minver
        id: version
        uses: thefringeninja/action-minver@2.0.0-preview1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3.1.0
        with:
          context: .
          file: WebApplication/Dockerfile
          push: true
          tags: "${{ env.REGISTRY }}/sopor10/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}"