name: 

on:
  pull_request:
    types: [closed, merged]
jobs:
  remove-preview:
    runs-on: ubuntu-latest
    name: Close
    steps:
      - name: Close
        uses: Azure/static-web-apps-deploy@c514ae36604047560e33605b78f71804967bfb7a
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"          