name: 

on:
  pull_request:
    types: [closed, merged]
jobs:
  remove-preview:
    runs-on: ubuntu-latest
    name: Close
    steps:
      - name: Close
        uses: Azure/static-web-apps-deploy@5c50db0011c6423f073843e7e22c3d0cb6c53920
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"          