name: Reusable steps (AKA composite action)
description: Demonstrate how to use reusable steps in a workflow
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v5
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x
    - name: Restore tools
      run: dotnet tool restore
    - name: Csharpier
      run: dotnet csharpier check .
    - name: Install workload
      run: dotnet workload install wasm-tools
    - name: Test
      run: dotnet test